/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day11;

/**
 *
 * @author ja_tu
 */
public class Kalkulators extends javax.swing.JPanel {
    
    private final Aprekini aprekini = new Aprekini();
    private int skaitlis1;
    private int skaitlis2;
    /**
     * Creates new form Kalkulators
     */
    public Kalkulators() {
        initComponents();
        rezultats.setText(String.valueOf(skaitlis1));
        aprekini.setOperacija("+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viens = new javax.swing.JButton();
        divi = new javax.swing.JButton();
        tris = new javax.swing.JButton();
        cetri = new javax.swing.JButton();
        pieci = new javax.swing.JButton();
        sesi = new javax.swing.JButton();
        septini = new javax.swing.JButton();
        astoni = new javax.swing.JButton();
        devini = new javax.swing.JButton();
        javax.swing.JButton nulle = new javax.swing.JButton();
        rezultats = new javax.swing.JLabel();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viens.setText("1");
        viens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viensActionPerformed(evt);
            }
        });
        add(viens, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 40));

        divi.setText("2");
        divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diviActionPerformed(evt);
            }
        });
        add(divi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, 40));

        tris.setText("3");
        tris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trisActionPerformed(evt);
            }
        });
        add(tris, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, 40));

        cetri.setText("4");
        cetri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetriActionPerformed(evt);
            }
        });
        add(cetri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, 40));

        pieci.setText("5");
        pieci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieciActionPerformed(evt);
            }
        });
        add(pieci, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 40));

        sesi.setText("6");
        sesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesiActionPerformed(evt);
            }
        });
        add(sesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 70, 40));

        septini.setText("7");
        septini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                septiniActionPerformed(evt);
            }
        });
        add(septini, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 40));

        astoni.setText("8");
        astoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astoniActionPerformed(evt);
            }
        });
        add(astoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, 40));

        devini.setText("9");
        devini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviniActionPerformed(evt);
            }
        });
        add(devini, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 40));

        nulle.setText("0");
        nulle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nulleActionPerformed(evt);
            }
        });
        add(nulle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 70, 40));

        rezultats.setBackground(new java.awt.Color(255, 255, 255));
        rezultats.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        add(rezultats, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 30));

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 70, 40));

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 70, 40));

        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 440, 40));

        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 40));

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void viensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viensActionPerformed
        setElementText("1");
    }//GEN-LAST:event_viensActionPerformed

    private void diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diviActionPerformed
        setElementText("2");
    }//GEN-LAST:event_diviActionPerformed

    private void trisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trisActionPerformed
        setElementText("3");
    }//GEN-LAST:event_trisActionPerformed

    private void cetriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetriActionPerformed
        setElementText("4");
    }//GEN-LAST:event_cetriActionPerformed

    private void pieciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieciActionPerformed
        setElementText("5");
    }//GEN-LAST:event_pieciActionPerformed

    private void sesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesiActionPerformed
        setElementText("6");
    }//GEN-LAST:event_sesiActionPerformed

    private void septiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_septiniActionPerformed
        setElementText("7");
    }//GEN-LAST:event_septiniActionPerformed

    private void astoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astoniActionPerformed
        setElementText("8");
    }//GEN-LAST:event_astoniActionPerformed

    private void deviniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviniActionPerformed
        setElementText("9");
    }//GEN-LAST:event_deviniActionPerformed

    private void nulleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nulleActionPerformed
        setElementText("0");
    }//GEN-LAST:event_nulleActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        skaitlis1 = aprekini.vienads(skaitlis1, skaitlis2);
        aprekini.setOperacija("+");
        setDefaultSkaitlis2();
    }//GEN-LAST:event_plusActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        skaitlis1 = aprekini.vienads(skaitlis1, skaitlis2);
        aprekini.setOperacija("=");
        setDefaultSkaitlis2();
    }//GEN-LAST:event_equalsActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        skaitlis1 = aprekini.vienads(skaitlis1, skaitlis2);
        aprekini.setOperacija("-");
        setDefaultSkaitlis2();
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        skaitlis1 = aprekini.vienads(skaitlis1, skaitlis2);
        aprekini.setOperacija("*");
        setDefaultSkaitlis2();
    }//GEN-LAST:event_multiplyActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
    }//GEN-LAST:event_clearActionPerformed

    private void setElementText(String vertiba){
        
        if(rezultats.getText().equals("0") || skaitlis2 == 0){
            rezultats.setText(vertiba);
        } else {
            rezultats.setText(String.valueOf(skaitlis2) + vertiba);
        }
        
        skaitlis2 = Integer.valueOf(rezultats.getText());
    }
    
    private void setDefaultSkaitlis2(){
        rezultats.setText(String.valueOf(skaitlis1));
        skaitlis2 = 0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton astoni;
    private javax.swing.JButton cetri;
    private javax.swing.JButton clear;
    private javax.swing.JButton devini;
    private javax.swing.JButton divi;
    private javax.swing.JButton equals;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton pieci;
    private javax.swing.JButton plus;
    private javax.swing.JLabel rezultats;
    private javax.swing.JButton septini;
    private javax.swing.JButton sesi;
    private javax.swing.JButton tris;
    private javax.swing.JButton viens;
    // End of variables declaration//GEN-END:variables
}
